name: Publish-ladybug-blender

on:
  push:
    branches: [ master ]

env:
  major: 0
  minor: 0
  name: ladybug-blender

jobs:
  activate:
    runs-on: ubuntu-latest
    steps:
    - name: Set env
      run: echo ok go

  build:
    needs: activate
    name: ladybug-blender
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2 # https://github.com/actions/setup-python
        with:
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          python-version: '3.11'
      - run: sudo apt install 2to3
      - run: echo ${{ env.DATE }}
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%y%m%d')"
      - name: Compile
        run: |
          make dist
      - name: Upload Zip file to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/ladybug-blender-${{steps.date.outputs.date}}.zip
          asset_name: ladybug-blender-${{steps.date.outputs.date}}.zip
          tag: "ladybug-blender-${{steps.date.outputs.date}}"
          overwrite: true
          body: "ladybug-blender build for ${{steps.date.outputs.date}}"
